# Generated by Django 2.1 on 2018-08-31 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autore', models.CharField(max_length=200)),
                ('titolo', models.CharField(max_length=200)),
                ('testo', models.TextField()),
                ('data_creazione_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_publicazione_post', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
